#baseURL = "https://yizenglistat.github.io/blog/"
baseURL = "https://yizengli.com/"
languageCode = 'en-us'
title = "Blog"
theme = "kiss"
#copyright = "&copy; <a href=\"https://github.com/yizenglistat\">Yizeng Li</a> 2017"
disqusShortname = "yizengli"
googleAnalytics = "UA-125871484-1"
Paginate = 3 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Yizeng Li" # Author full name
authorEmail = "1994yizeng@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Blog" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.social]
github = "yizenglistat"
email = "1994yizeng@gmail.com"
rss = "index.xml" # Add this to show RSS button in social.
kofi = "yizenglistat"

[params.social.config]
platforms = ["github","kofi","email","rss"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true


# for search

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
# for menu

[menu]
	[[menu.nav]]
	identifier = "search"
	name = "Search"
	url = "/search/"
	weight = 4
	# [[menu.nav]]
	# identifier = "series"
	# name = "Series"
	# url = "/series/"
	# weight = 3
	[[menu.nav]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2
	[[menu.nav]]
	identifier = "home"
	name = "Home"
	url = "/post/"
	weight = 1

