#baseURL = "https://yizenglistat.github.io/blog/"
baseURL = "https://yizengli.com/"
languageCode = 'en-us'
title = "yizengli.com"
relativeURLs = true
uglyURLs = true

#copyright = "&copy; <a href=\"https://github.com/yizenglistat\">Yizeng Li</a> 2017"
disqusShortname = "yizengli"
googleAnalytics = "UA-125871484-1"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.selected]
numPosts = 3
showHot = false
toptags = 5
topseries = 2

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Yizeng Li"
authorEmail = "yizeng@yizengli.com"

[params.assets]
customCSS = ["css/custom.css"]

[params.comments]
utterancesRepo = "yizenglistat/blog"
utterancesIssueTerm = "pathname"

[params.info]
adsense = "9941714392478176" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "yizengli.com" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.social]
github = "yizenglistat"
email = "yizeng@yizengli.com"
rss = "index.xml" # Add this to show RSS button in social.
kofi = "yizenglistat"
twitter = "yizenglistat"

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
   tag = "tags"
   category = "categories"

[blackfriday]
hrefTargetBlank = true


# for search

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
# for menu

[menu]
	# [[menu.nav]]
	# identifier = "search"
	# name = "Search"
	# url = "/search/"
	# weight = 5
	# [[menu.nav]]
	# identifier = "categories"
	# name = "Series"
	# url = "/categories/"
	# weight = 4
	[[menu.nav]]
	identifier = "newsletter"
	name = "Newsletter"
	url = "/newsletter/"
	weight = 3
	[[menu.nav]]
	identifier = "posts"
	name = "Writing"
	url = "/posts/"
	weight = 2
	[[menu.nav]]
	identifier = "home"
	name = "Root"
	url = "/"
	weight = 1

# code fence

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'solarized-dark'
    tabWidth = 4